app:
    jwt:
        expirationDateAfterDays: 20
        secretKey: ssdsdsd
        tokenPrefix: Bearer
server:
    error:
        include-message: always
    port: 8000
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
#        username: postgres
#        password: postgres

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL10Dialect
        hibernate:
            ddl-auto: update
        show-sql: true
springdoc:
    swagger-ui:
        path: /swagger

